# Generated by Django 4.2.7 on 2025-12-01 18:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hippodrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ипподрома')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Ипподром',
                'verbose_name_plural': 'Ипподромы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Жокей',
                'verbose_name_plural': 'Жокеи',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('jockey', 'Жокей'), ('admin', 'Администратор')], default='user', max_length=10, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('jockey', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='racing.jockey', verbose_name='Профиль жокея')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('gender', models.CharField(choices=[('M', 'Жеребец'), ('F', 'Кобыла')], max_length=1, verbose_name='Пол')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Лошадь',
                'verbose_name_plural': 'Лошади',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название состязания')),
                ('hippodrome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.hippodrome', verbose_name='Ипподром')),
            ],
            options={
                'verbose_name': 'Состязание',
                'verbose_name_plural': 'Состязания',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Занятое место')),
                ('time_result', models.DurationField(verbose_name='Показанное время')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.competition', verbose_name='Состязание')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.horse', verbose_name='Лошадь')),
                ('jockey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.jockey', verbose_name='Жокей')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'unique_together': {('competition', 'position')},
            },
        ),
    ]
