version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: racing-club-db
    environment:
      - POSTGRES_DB=racing_club_db
      - POSTGRES_USER=racing_user
      - POSTGRES_PASSWORD=racing_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - racing-network
    restart: unless-stopped

  # Django Racing Club Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: racing-club-web
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./logs:/app/logs
    environment:
      - DEBUG=True
      - POSTGRES_DB=racing_club_db
      - POSTGRES_USER=racing_user
      - POSTGRES_PASSWORD=racing_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - racing-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  racing-network:
    driver: bridge
